- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.6.0
  hooks:
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: flake8
  - id: pretty-format-json
    args: ['--autofix']
  - id: requirements-txt-fixer
  - id: trailing-whitespace
